FROM inexus.ixxus.co.uk:28443/ixxus/alfresco-share:5.1.2
MAINTAINER Alex Lu (alex.lu@ixxus.com)

ADD target/*.jar $TOMCAT_HOME/webapps/share/WEB-INF/lib/
#ADD target/lib/*.jar $TOMCAT_HOME/webapps/share/WEB-INF/lib/
